wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699994800.632779
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      4: 3.10.12
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
